---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "l3-banks-consortium-network-config"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "L3 - Banks Consortium HLF Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see idfc.yaml, hsbc.yaml and idbi.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  mychannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("lic" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.banksconsortium.com

    # Required. list of peers from participating orgs
    peers:
      peer0.idfc.banksconsortium.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer1.idfc.banksconsortium.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.hsbc.banksconsortium.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.hsbc.banksconsortium.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.idbi.banksconsortium.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.idbi.banksconsortium.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
    # [Optional]. what chaincodes are expected to exist on this channel? The appmanufactureration can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - mycc:v0

#
# list of participating organizations in this network
#
organizations:
  idfc:
    mspid: idfcMSP

    peers:
      - peer0.idfc.banksconsortium.com
      - peer1.idfc.banksconsortium.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca-idfc

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/idfc.banksconsortium.com/users/Admin@idfc.banksconsortium.com/msp/keystore/0e9ef3beea26ac6325dd7566467dc6f6c961db1e198a90a570a03c4e557d2ffb_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/idfc.banksconsortium.com/users/Admin@idfc.banksconsortium.com/msp/signcerts/Admin@idfc.banksconsortium.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  hsbc:
    mspid: hsbcMSP
    peers:
      - peer0.hsbc.banksconsortium.com
      - peer1.hsbc.banksconsortium.com
    certificateAuthorities:
      - ca-hsbc
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/hsbc.banksconsortium.com/users/Admin@hsbc.banksconsortium.com/msp/keystore/460e31411b2ce7ec2dd44df525489be2c3d05a2ea659611683dab1d9a0be169a_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/hsbc.banksconsortium.com/users/Admin@hsbc.banksconsortium.com/msp/signcerts/Admin@hsbc.banksconsortium.com-cert.pem

  idbi:
    mspid: idbiMSP
    peers:
      - peer0.idbi.banksconsortium.com
      - peer1.idbi.banksconsortium.com
    certificateAuthorities:
      - ca-idbi
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/idbi.banksconsortium.com/users/Admin@idbi.banksconsortium.com/msp/keystore/874c60340aba00747aa7897bfec82eabcb188729eb1b3ae5b937f700e07778bd_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/idbi.banksconsortium.com/users/Admin@idbi.banksconsortium.com/msp/signcerts/Admin@idbi.banksconsortium.com-cert.pem
#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.banksconsortium.com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.banksconsortium.com

    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/banksconsortium.com/orderers/orderer.banksconsortium.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.idfc.banksconsortium.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer0.idfc.banksconsortium.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/idfc.banksconsortium.com/peers/peer0.idfc.banksconsortium.com/tls/ca.crt

  peer1.idfc.banksconsortium.com:
    url: grpcs://localhost:7056
    grpcOptions:
      ssl-target-name-override: peer1.idfc.banksconsortium.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/idfc.banksconsortium.com/peers/peer1.idfc.banksconsortium.com/tls/ca.crt

  peer0.hsbc.banksconsortium.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer0.hsbc.banksconsortium.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/hsbc.banksconsortium.com/peers/peer0.hsbc.banksconsortium.com/tls/ca.crt

  peer1.hsbc.banksconsortium.com:
    url: grpcs://localhost:8056
    grpcOptions:
      ssl-target-name-override: peer1.hsbc.banksconsortium.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/hsbc.banksconsortium.com/peers/peer1.hsbc.banksconsortium.com/tls/ca.crt

  peer0.idbi.banksconsortium.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.idbi.banksconsortium.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/idbi.banksconsortium.com/peers/peer0.idbi.banksconsortium.com/tls/ca.crt

  peer1.idbi.banksconsortium.com:
    url: grpcs://localhost:9056
    eventUrl: grpcs://localhost:8058
    grpcOptions:
      ssl-target-name-override: peer1.idbi.banksconsortium.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/idbi.banksconsortium.com/peers/peer1.idbi.banksconsortium.com/tls/ca.crt  

# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Appidfcation may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-idfc:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/idfc.banksconsortium.com/ca/ca.idfc.banksconsortium.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-idfc

  ca-hsbc:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/hsbc.banksconsortium.com/ca/ca.hsbc.banksconsortium.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-hsbc


  ca-idbi:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/idbi.banksconsortium.com/ca/ca.idbi.banksconsortium.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-idbi

